### ISSUE TITLE
example from view doc not working

### ISSUE THREAD

**Issue by bsbak** [astaxie/beego#2481]
go 1.8
beego 1.7.2
windows 7 sp1

example from https://beego.me/docs/mvc/view/view.md -> contents "Another Aproach" not working... Need refresh page many times to see result, why? With examples above all fine.

**Comment by astaxie** [comment]
I don't know what you are talking about.

**Comment by bsbak** [comment]
> I don't know what you are talking about.
here a video to explain "what you are talking about".
[<iframe class="tscplayer_inline embeddedObject" name="tsc_player" scrolling="no" frameborder="0" type="text/html" style="overflow:hidden;" src="https://www.screencast.com/users/kenwo0d.indaclub/folders/Camtasia Studio/media/acef081c-1458-4823-a9ea-3546359a3e56/embed" height="640" width="480" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>](url)

**Comment by bsbak** [comment]
**astaxie** please help me! Why that example not working? I tried a lot of options but still can not understand why does not it work!

**Comment by astaxie** [comment]
@bsbak I just watch the video. It looks so weird. The content is changed. I have no ideas now

**Comment by bsbak** [comment]
I just was copy example from your site and paste to clear project created by bee tool, the content not changed!?

**Comment by bsbak** [comment]
I was tryed without beego by clean go:
main.go
`package main

import (
	"html/template"
	"net/http"
)

func main() {
	http.HandleFunc("/", IndexHandler)
	http.ListenAndServe(":8081", nil)
}

func IndexHandler(w http.ResponseWriter, req *http.Request) {
	t, _ := template.ParseFiles("layout.html", "index.html")
	t.Execute(w, nil)
}`
layout.html
`<html>
<head></head>
<body>
{{block "content" .}}{{end}}
</body>
</html>`

index.html
`{{define "content"}}test{{end}}`

That works fine! But that example with beego not working, and cant understand why, that problem in beego?
If you dont wanna help me,  i will not write anything...

**Comment by tpobozy** [comment]
Same issue here. Sample from docs doesn't work. 
ref: https://beego.me/docs/mvc/view/view.md#another-approach

**Comment by ysqi** [comment]
It is work well for v1.6.0 , bad for v1.7.0

**Comment by tpobozy** [comment]
It doesn't work in v1.8 as well

**Comment by pablolagos** [comment]
Hello. Same problem here. Version 1.8

**Comment by astaxie** [comment]
@ysqi Could you help to reproduce it and make a hotfix?

**Comment by ysqi** [comment]
hi @astaxie ,I'm not sure the bug from where, but you need check PR #1752

**Comment by JessonChan** [comment]
@bsbak can you have a test a my new pr?

**Comment by iwondory** [comment]
The same issue is reproduced here.

After upgrading Go from 1.7.5 to 1.8, I am suffering from page refresh issue.
Eventually, I downgrade Go version from 1.8 to 1.7.5, and then it works fine.

**Comment by iwondory** [comment]
@astaxie Thank for your supports. Fantastic beego framework !

**Comment by ysqi** [comment]
what happen？ it is work well for Go1.7 ,but not for Go1.8, example src [bsbak.zip](https://github.com/astaxie/beego/files/887384/bsbak.zip)

![image](https://cloud.githubusercontent.com/assets/2821085/24575577/a31b94e4-16dc-11e7-97fa-fdba2a665a98.png)
 
├── Beego     : 1.7.0
├── GoVersion : go1.7
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : ***
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Saturday, 1 Apr 2017

**Comment by astaxie** [comment]
@bsbak @tpobozy @ysqi @pablolagos It's the same issue #2544 which is caused by Go1.8. It's already fixed in Go1.8.1. Please help to check whether it's still the problem in Go1.8.1. Thanks

**Comment by brainplusplus** [comment]
still not working 
im using : 
├── Beego     : 1.9.2
├── GoVersion : go1.9.1
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : /Users/brainplusplus/Project/nbs/dana/middleware
├── GOROOT    : /usr/local/go/1.9.1
├── Compiler  : gc
└── Date      : Friday, 2 Feb 2018
