### ISSUE TITLE
No Model Definition for swagger for beego api

### ISSUE THREAD

**Issue by RajeshKumar1990** [astaxie/beego#2581]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.2

├── Beego     : 1.8.0
├── GoVersion : go1.6.4
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Projects\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Friday, 21 Apr 2017

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=C:\Projects\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
This is how my swagger look like

![swagger1](https://cloud.githubusercontent.com/assets/22511293/25267471/78de21ee-26a7-11e7-9513-ca22cf90a54a.JPG)
I haven't changed anything here.This is the result of the default object model present after the API creation.
All i did is
```
bee api testapi
bee run -downdoc=true -gendoc=true 
```

I cant see any model definitions in it.
4. What did you expect to see?
Expected to see the model definitions 

5. What did you see instead?
I see the empty curly braces

**Comment by Vetcher** [comment]
Same empty models for me. `bee version` and `bee env` are the same, except NumCPU is 8.

**Comment by Vetcher** [comment]
1. My `bee version` is
```
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.2

├── Beego     : 1.8.0
├── GoVersion : go1.8
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : C:\Work\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Monday, 24 Apr 2017
```    
2. My `go env` is
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Work\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```
3. 
4.  I expect to see this
![image](https://cloud.githubusercontent.com/assets/10078725/25334308/d71381d6-28f6-11e7-8cee-cdc15829ae0e.png)

it works with old bee:    
`bee version`
```
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.5.2

├── Beego     : 1.8.0
├── GoVersion : go1.7.1
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : C:\Work\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Monday, 24 Apr 2017
```

5. Instead, I looks like this
![image](https://cloud.githubusercontent.com/assets/10078725/25334270/a0902984-28f6-11e7-8f52-b3ef5666c6e2.png)

P.S. `bee generate docs`:
```
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.2
2017/04/24 14:09:08 WARN     ▶ 0001 Cannot find the object: models.Comment
2017/04/24 14:09:08 WARN     ▶ 0002 Cannot find the object: models.Comment
2017/04/24 14:09:08 WARN     ▶ 0003 Cannot find the object: models.Comment
2017/04/24 14:09:08 WARN     ▶ 0004 Cannot find the object: models.Comment
2017/04/24 14:09:08 WARN     ▶ 0005 Cannot find the object: models.Comment
2017/04/24 14:09:08 WARN     ▶ 0006 Cannot find the object: models.RecomendCourses
2017/04/24 14:09:08 WARN     ▶ 0007 Cannot find the object: models.RecomendCourses
...
~ 50 lines of "Cannot find the object"
...
2017/04/24 14:09:08 WARN     ▶ 0102 Cannot find the object: models.Task
2017/04/24 14:09:08 WARN     ▶ 0103 Cannot find the object: models.Task
2017/04/24 14:09:08 SUCCESS  ▶ 0104 Docs successfully generated!
```

**Comment by astaxie** [comment]
it works on Mac. I will try to reproduce it in window

![image](https://cloud.githubusercontent.com/assets/233907/25336116/9c337f58-2928-11e7-8cae-e01a6ca2c2b5.png)

**Comment by astaxie** [comment]
fixed in beego/bee develop branch.

**Comment by MrrDai** [comment]
我遇到了同样的问题，操作系统ubuntu-17.04
bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.1

├── Beego     : 1.8.3
├── GoVersion : go1.8
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /home/rd/work/git/
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Friday, 9 Jun 2017


bee generate docs 
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.1
2017/06/09 12:17:15 WARN     ▶ 0001 Cannot find the object: models.Object
2017/06/09 12:17:15 WARN     ▶ 0002 Cannot find the object: models.Object
2017/06/09 12:17:15 WARN     ▶ 0003 Cannot find the object: models.Object
2017/06/09 12:17:15 WARN     ▶ 0004 Cannot find the object: models.Object
2017/06/09 12:17:15 WARN     ▶ 0005 Cannot find the object: models.Object
2017/06/09 12:17:15 WARN     ▶ 0006 Cannot find the object: models.User
2017/06/09 12:17:15 WARN     ▶ 0007 Cannot find the object: models.User
2017/06/09 12:17:15 WARN     ▶ 0008 Cannot find the object: models.User
2017/06/09 12:17:15 WARN     ▶ 0009 Cannot find the object: models.User
2017/06/09 12:17:15 WARN     ▶ 0010 Cannot find the object: models.User


我将beego/bee 切换到develop分之还是遇到同样问题

**Comment by abhayaveer** [comment]
I still see the issue in bee 1.11 version. Astaxie.. could you please check
